spring:
  application:
    name: factura

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/factura-app

  datasource:
    url: jdbc:postgresql://localhost:5432/factura
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true

